---
- name: Deploy Nginx
  hosts: webservers
  become: true
  vars:
    site_root: /var/www/html

  tasks:
    - name: Update apt cache and install nginx + curl
      apt:
        name:
          - nginx
          - curl
        state: present
        update_cache: yes

    - name: Ensure site root directory exists
      file:
        path: "{{ site_root }}"
        state: directory
        mode: '0755'

    - name: Deploy basic index.html
      copy:
        dest: "{{ site_root }}/index.html"
        content: |
          <html>
          <head><title>My first Ansible Class Assignment</title></head>
          <body>
            <h1>Hello, my name is Joseph Folorunso</h1>
            <p>This page is deployed automatically with Ansible.</p>
          </body>
          </html>

    - name: Start and enable Nginx with service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Show final URL
      debug:
        msg: "Your site is available at http://{{ ansible_host }}/"